import {
    HomeIcon,
    ExploreOutlinedIcon,
    ElectricBoltIcon,
    SubscriptionsOutlinedIcon,
    VideoLibraryOutlinedIcon,
    HistoryOutlinedIcon,
    SlideshowOutlinedIcon,
    AccessTimeOutlinedIcon,
    ThumbUpOutlinedIcon,
    ExpandMoreOutlinedIcon,
    LocalFireDepartmentOutlinedIcon,
    MusicNoteOutlinedIcon,
    StreamOutlinedIcon,
    SportsEsportsOutlinedIcon,
    EmojiEventsOutlinedIcon,
} from "./Imports";


export const sidebarItems = [
    { icon: HomeIcon, text: "Home" , hideOnSm:false},
    { icon: ExploreOutlinedIcon, text: "Explore" , hideOnSm:true},
    { icon: ElectricBoltIcon, text: "Shorts" , hideOnSm:false},
    { icon: SubscriptionsOutlinedIcon, text: "Subscriptions" , hideOnSm:false},
    {text: "break" , hideOnSm:true},
    { icon: VideoLibraryOutlinedIcon, text: "Library" , hideOnSm:false},
    { icon: HistoryOutlinedIcon, text: "History" , hideOnSm:true},
    { icon: SlideshowOutlinedIcon, text: "Your videos" , hideOnSm:true, signedIn:true},
    { icon: AccessTimeOutlinedIcon, text: "Watch later" , hideOnSm:true,  signedIn:true},
    { icon: ThumbUpOutlinedIcon, text: "Liked videos" , hideOnSm:true,  signedIn:true},
    { icon: ExpandMoreOutlinedIcon, text: "Show more" , hideOnSm:true,  signedIn:true},
    {text: "break" , hideOnSm:true, signedIn: true},
    {text:'Subscriptions', hideOnSm:true, signedIn:true},
    {text:'Sign In', hideOnSm:true, signedIn:true},
    {text: "break" , hideOnSm:true},
    {text:'Explore', hideOnSm:true},
    { icon: LocalFireDepartmentOutlinedIcon, text: "Trending" , hideOnSm:true},
    { icon: MusicNoteOutlinedIcon, text: "Music" , hideOnSm:true},
    { icon: StreamOutlinedIcon, text: "Live" , hideOnSm:true},
    { icon: SportsEsportsOutlinedIcon, text: "Gaming" , hideOnSm:true},
    { icon: EmojiEventsOutlinedIcon, text: "Sports" , hideOnSm:true},
];  

export const youtubeCategories = [
    "All",
    "Entertainment",
    "Music",
    "Gaming",
    "Sports",
    "Education",
    "Beauty and Fashion",
    "Technology",
    "Travel and Adventure",
    "Health and Fitness",
    "Cooking and Food",
    "DIY and Crafts",
    "Comedy",
    "Lifestyle",
    "News and Politics",
    "Science and Technology"
];


export const themes= [
    "youtubeDark",
    "youtubeLight",
    "business",
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
]